#!/usr/bin/env python3
"""
Inject generated audio clips into eclipse.html.

Reads audio-clips.js (generated by generate-audio.py) and replaces
the empty AUDIO_CLIPS object in eclipse.html with the base64-encoded clips.

Usage:
    python3 inject-audio.py

This modifies eclipse.html in place (creates a backup first).
"""

import re
import shutil
import sys
from pathlib import Path

HTML_FILE = Path("eclipse.html")
JS_FILE = Path("audio-clips.js")
BACKUP_FILE = Path("eclipse.html.bak")


def main():
    if not HTML_FILE.exists():
        print(f"✗ {HTML_FILE} not found")
        sys.exit(1)
    
    if not JS_FILE.exists():
        print(f"✗ {JS_FILE} not found. Run generate-audio.py first.")
        sys.exit(1)
    
    # Read the JS file and extract just the AUDIO_CLIPS object
    js_content = JS_FILE.read_text(encoding="utf-8")
    
    # Extract the object assignment (skip comments)
    match = re.search(r"const AUDIO_CLIPS = ({.*?});", js_content, re.DOTALL)
    if not match:
        print("✗ Could not parse AUDIO_CLIPS from audio-clips.js")
        sys.exit(1)
    
    clips_json = match.group(1)
    
    # Read eclipse.html
    html = HTML_FILE.read_text(encoding="utf-8")
    
    # Find and replace the AUDIO_CLIPS block
    # Pattern: from "const AUDIO_CLIPS = {" to the closing "};"
    pattern = r"const AUDIO_CLIPS = \{[^}]*(?:\{[^}]*\}[^}]*)*\};"
    
    replacement = f"const AUDIO_CLIPS = {clips_json};"
    
    new_html, count = re.subn(pattern, replacement, html, count=1)
    
    if count == 0:
        print("✗ Could not find AUDIO_CLIPS in eclipse.html")
        print("  Make sure the AUDIO_CLIPS object exists in the file.")
        sys.exit(1)
    
    # Backup
    shutil.copy2(HTML_FILE, BACKUP_FILE)
    print(f"✓ Backup: {BACKUP_FILE}")
    
    # Write
    HTML_FILE.write_text(new_html, encoding="utf-8")
    
    old_size = len(html) / 1024
    new_size = len(new_html) / 1024
    print(f"✓ Injected audio into {HTML_FILE}")
    print(f"  Size: {old_size:.0f} KB → {new_size:.0f} KB (+{new_size - old_size:.0f} KB)")
    print(f"  Audio data adds ~{(new_size - old_size)/1024:.1f} MB to the file")


if __name__ == "__main__":
    main()
